adapter:
  host: 0.0.0.0
  port: 8092
  test_file: ./tests/load_tests/locustfile_demo.py
  type: locust
orchestrator:
  max_users: 12
  max_wait_time: 123
  monitoring_interval: 52
  spawn_rate: 1000
strategy:
  error_threshold: 10.0
  initial_users: 10
  step_multiplier: 10.0
  type: break_point
