adapter:
  host: 0.0.0.0
  port: 8091
  test_file: ./tests/load_tests/locustfile_mock.py
  type: locust
orchestrator:
  max_users: null
  monitoring_interval: 5
  spawn_rate: 1000
strategy:
  initial_users: 1
  step_multiplier: 1.5
  threshold_count: 3
  type: degradation_search
  window_size: 5
