adapter:
  host: 0.0.0.0
  port: 8092
  test_file: ./tests/load_tests/locustfile.py
  type: locust
orchestrator:
  max_users: 1000
  monitoring_interval: 5
  spawn_rate: 1
strategy:
  target_rps: 500.0
  test_duration: 300
  tolerance: 0.05
  type: target_rps
